source 'https://rubygems.org'

gem 'jekyll', '~> 4.2.0'
gem 'jekyll-theme-primer'
gem 'jekyll-seo-tag'
gem 'jekyll-github-metadata'
gem 'jekyll-paginate'
gem 'jekyll-relative-links'
gem 'jekyll-optional-front-matter'
gem 'jekyll-readme-index'
gem 'jekyll-default-layout'
gem 'jekyll-titles-from-headings'
gem 'kramdown-parser-gfm'
