name: Build and Deploy Jekyll Site

on:
  push:
    branches:
      - main
      - latest-version-2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Install Bundler 1.x
        run: gem install bundler -v '~>1.17'

      - name: Clear Bundler and Gem caches
        run: |
          rm -rf vendor/bundle
          rm -rf ~/.bundle/cache
          rm -rf ~/.gem/cache
          bundle config set --local path 'vendor/bundle'

      - name: Install dependencies with force
        run: bundle install --jobs 4 --force

      - name: Build the Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
